export {default as HomePage} from './home'
export {default as AboutPage} from './about'
export {default as ManageKit} from './manager/manage-kit'
export {default as ManageLab} from './manager/manage-lab'
export {default as ManageKitDeliveryDetail} from './manager/manage-kit-delivery-detail'