export const PATH = {
  /* GUEST PATHS */
  HOME: "/",
  LOGIN: "/login",
  ABOUT: "/about",
  REGISTER: "/register",
  TERMS: "/terms",
  POLICY: "/terms/policy",
  GUIDELINES: "/terms/guidelines",
  SUPPORT: "/support",
  BLOGS: "/blogs",
  BLOG_DETAIL: "/blog/:id",
  CONTACT: "/contact",
  TEACHING: "/teaching",
  NAME_CATEGORY: "/category",
  SITEMAP: "/sitemap",
  NOTFOUND: "/notfound",
  COURSE_DETAILS: "/course/:_id",
  COURSE_DETAIL: "/course/:id",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_TOKEN: "/verify-email/:token",
  USER_DETAIL: "/user/:id",
  INTERNAL_SERVER_ERROR: "/internal-server-error",
  //Staff
  STAFF: '/staff/*',
  STAFF_LOGIN : '/manager/login',
  STAFF_HOME: 'dashboard',
  STAFF_DASHBOARD: '/staff/dashboard',
  //Manager
  MANAGER: '/manager/*',
  MANAGER_LOGIN : '/manager/login',
  MANAGER_HOME: 'dashboard',
  MANAGER_MANAGE_KIT: "/manager/manage-kit",
  MANAGER_KIT_DELIVERY_DETAIL: "manage-kit-delivery-detail",
  MANAGER_KIT_DELIVERY: "manage-kit-delivery",
  MANAGER_LAB: "manage-lab",
  MANAGER_KIT: "manage-kit",
  MANAGER_KIT_ID: "manage-kit/:id",
  MANAGER_USER: "manage-user",
  MANAGER_DASHBOARD: "/manager/dashboard",
  //admin
  ADMIN: '/admin/*',
  ADMIN_LOGIN: "/admin/login",
  ADMIN_HOME: "dashboard",
  ADMIN_MANAGE_USER: 'manage-users',
  ADMIN_MANAGE_BLOG: 'manage-blogs',
  ADMIN_MANAGE_CATEGORY: 'manage-categories',
  ADMIN_DASHBOARD: "/admin/dashboard",
  /* IMG */
  AVATAR:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8PyKYrBKAWWy6YCbQzWQcwIRqH8wYMPluIZiMpV1w0NYSbocTZz0ICWFkLcXhaMyvCwQ&usqp=CAU",
};